<?php

namespace AppBundle\Repository;

/**
 * ChatBotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatBotRepository extends \Doctrine\ORM\EntityRepository
{
}
