<?php

namespace AppBundle\Repository;

/**
 * LigneTherapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneTherapRepository extends \Doctrine\ORM\EntityRepository
{
}
