<?php

namespace AppBundle\Repository;

/**
 * MobileTerminatedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobileTerminatedRepository extends \Doctrine\ORM\EntityRepository
{
}
