<?php

namespace AppBundle\Repository;

/**
 * PhonebookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhonebookRepository extends \Doctrine\ORM\EntityRepository
{
}
