<?php

namespace AppBundle\Repository;

/**
 * SenderNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SenderNameRepository extends \Doctrine\ORM\EntityRepository
{
}
